### ISSUE TITLE
Q: jdk.java.net 17 no longer available. Should only use "EA" and "GA" with jdk.java.net rather than 17,18,19?

### ISSUE THREAD

**Issue by rbygrave** [oracle-actions/setup-java#24]
I have a bunch of "EA Builds" setup using `jdk.java.net` and a version matrix of `17,18,19`.

Now obviously `18` has been released and so I can understand that `17` is no longer part of the "EA build family". This makes me think that the recommendation should be use **EA**, **GA** (+ loom, panama etc) and effectively is is not a good idea to use specific versions like 17,18,19 ... unless people expect to edit their "EA Builds" every 6 months?

- Can I confirm that `jdk.java.net` no longer hosts build versions after the next version has gone GA (17 in this case)? 
- Are people just expected to use EA and GA?  (If so maybe the docs should be tweaked for jdk.java.net)

Thanks, Rob.

**Comment by delabassee** [comment]
@rbygrave It's a bit more complicated as there's an additional dimension, i.e. LTS.

Regarding EA builds, you should only use EA builds until that specific version goes GA. Having said that, we can imagine a few use-cases where it could make sense to use (older) EA builds, ex. find a regression between EA and GA, or between 2 different EA builds. To address that, we are working on making the EA builds archive available for a longer period.

**Comment by rbygrave** [comment]
Ok. I've swapped over all my "EA Builds" to use **EA** and **GA** and I'm pretty comfortable that is the right thing to do (so yes let's close this I think).

> LTS

Yes, I still have _other builds_ (what I'd describe as _"non-EA builds"_) that desire explicitly using **11** (and **17**) as they are libraries that target those "LTS releases".  My expectation is that I'm not expecting to ever get those LTS versions via `jdk.java.net`.

I think we can close this one. Thanks.
