### ISSUE TITLE
Using GA, got - Error: The string '18.0.1.1' is not valid SemVer notation for a Java version.

### ISSUE THREAD

**Issue by rbygrave** [oracle-actions/setup-java#25]
```
Run oracle-actions/setup-java@v1
  with:
    website: jdk.java.net
    release: GA
    version: latest
    install: true
Run JAVA=$JAVA_HOME_17_X64/bin/java
  JAVA=$JAVA_HOME_17_X64/bin/java
  DOWNLOAD=$GITHUB_ACTION_PATH/src/Download.java
  if [ ! -z "" ]; then
    $JAVA $DOWNLOAD 
  else
    $JAVA $DOWNLOAD jdk.java.net GA latest
  fi
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
Archive openjdk-18.0.1.1_linux-x64_bin.tar.gz in file:///home/runner/.oracle-actions/setup-java/3eac1378/
Run actions/setup-java@v3
  with:
    java-version: 18.0.1.1
    distribution: jdkfile
    jdkFile: /home/runner/.oracle-actions/setup-java/3eac1378/openjdk-18.0.1.1_linux-x64_bin.tar.gz
    java-package: jdk
    architecture: x64
    check-latest: false
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
    overwrite-settings: true
    job-status: success
Error: The string '18.0.1.1' is not valid SemVer notation for a Java version. Please check README file for code snippets and more detailed information
```

The build log is at: https://github.com/ebean-orm/ebean/runs/6267071973?check_suite_focus=true

**Comment by sormuras** [comment]
Thanks for reporting this issue, Rob.

The documentation of [actions/setup-java](https://github.com/actions/setup-java/blob/bae3140877a4e25b7fb2aa73013c6245709d0fc0/action.yml#L7) says:
```yml
  java-version:
    description: 'The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file'
```

I guess, "a whole Java version" of `18.0.1.1` is not (yet) supported by `actions/setup-java@3`, or that the underlying semver parser has an issue.

There are some temporary mitigation paths `oracle-actions/setup-java` can take:
- Only pass `x.y.z` as the version to `actions/setup-java@3`. Here, omit the trailing `.1` from `18.0.1.1`: `18.0.1`
- Downgrade to `actions/setup-java@2` and test whether `18.0.1.1` are supported.

**Comment by sormuras** [comment]
Also errors for `oracle.com`, when using specific archived version `18.0.1.1`. Using the default `latest` as version works, as its version resolves to only the feature number `18`.

**Comment by sormuras** [comment]
Rob, please restart the failed workflow run(s). They should work now.

**Comment by rbygrave** [comment]
Thanks.  Yes, re-run and all good.  Awesome, thanks !!
