### ISSUE TITLE
Update to use GitHub's environment files

### ISSUE THREAD

**Issue by sormuras** [oracle-actions/setup-java#43]
https://github.com/oracle-actions/setup-java/blob/2e3562c72585cd036e42706589f272ed8d08f24d/src/Download.java#L221

> Action and workflow authors who are using `save-state` or `set-output` via stdout should update to use the new environment files.

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by derlin** [comment]
Are you suggesting to modify this line with the following ?
```java
System.out.printf("echo \"%s=%s\" >> $GITHUB_OUTPUT%n", name, value); 
```

Or do you see other changes that are necessary ?

(I am interested in taking this issue)

**Comment by sormuras** [comment]
Yes, as far as I can tell, it's the only line that requires a change:
![image](https://user-images.githubusercontent.com/2319838/195156023-6153d223-cafa-4c05-b35d-0466a3603263.png)

Your proposed change woudn't work on Windows (`cmd.exe` nor PowerShell), would it?
Perhaps using NIO's `Files.write[String]()` is platform-agnostic solution. Something like:
```java
var output = Path.of(System.env...);
Files.write(
    output,
    List.of(name + "=" + value),
    StandardCharsets.UTF_8,
    StandardOpenOption.CREATE,
    StandardOpenOption.APPEND,
    StandardOpenOption.WRITE);
```

Before you hack away and create a pull request, I first need to clarify whether and how contributions can be submitted.

**Comment by sormuras** [comment]
> Starting today runner version 2.298.2 will begin to warn you if you use the `save-state` or `set-output` commands via stdout.

Warnings are now in place.

![image](https://user-images.githubusercontent.com/2319838/195270367-d1c3ae5d-f2a0-4909-b7aa-75daff38b535.png)

**Comment by sormuras** [comment]
@derlin I am taking care of this issue because I want to get rid of the warnings as soon as possible. That's why I removed the _good first issue_ label and filed:
- #46

**Comment by sormuras** [comment]
Outputs are empty?!

![image](https://user-images.githubusercontent.com/2319838/196765828-cf07cb64-1db7-4af2-ae14-04fdb23b21c7.png)

**Comment by sormuras** [comment]
Fixed by https://github.com/oracle-actions/setup-java/commit/e81158a0e3112b4b04c18bbdcd2b276a6df82436
