### ISSUE TITLE
Add support for Oracle GraalVM

### ISSUE THREAD

**Issue by Thihup** [oracle-actions/setup-java#56]

**Comment by delabassee** [comment]
Already available via https://github.com/marketplace/actions/github-action-for-graalvm

**Comment by Thihup** [comment]
Now that Oracle GraalVM is available on oracle.com, shouldn't this plugin also support it?

https://www.oracle.com/java/technologies/downloads/#graalvmjava20

The URL is very similar to the JDK

https://download.oracle.com/java/20/latest/jdk-20_linux-x64_bin.tar.gz
https://download.oracle.com/graalvm/20/latest/graalvm-jdk-20_linux-x64_bin.tar.gz

**Comment by fniephaus** [comment]
You may want to take a look at https://github.com/actions/setup-java/pull/501.
